---

- name: Include pull secrets
  include_vars:
    file: pull-secrets.vault

# Create secret objects for each image pull secret defined.
# These are typically used to pull container images
# from private registries.

- name: Create image pull secrets
  k8s:
    definition: "{{ lookup('template', 'secret-imagepull.yaml.j2') }}"
    wait: yes
  vars:
    pull_name: "{{ item.name }}"
    pull_secret: "{{ item.secret }}"
  with_items: "{{ fs_pull_secrets }}"

- name: Deploy Fragnet UI objects
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ fs_pod_ready_timeout }}"
  loop:
  - configmap-search
  - configmap-ui
  - deployment-ui
