---

# Sets a number of facts: -
#
# - keycloak_realm_manager_fact
# - keycloak_realm_manager_password_fact

- name: Assert variables
  assert:
    that:
    - ir_namespace|length > 0
    - fs_realm|length > 0

- name: Get Keycloak Realm manager secrets (from '{{ ir_namespace }}' namespace)
  k8s_info:
    kind: Secret
    name: manager-{{ fs_realm }}
    namespace: "{{ ir_namespace }}"
  register: krm_s_result

- name: Assert Keycloak realm manager secrets
  assert:
    that: krm_s_result.resources|length == 1

# Extract Realm manager details from pre-deployed secrets...

- name: Set Keycloak realm manager facts (from secret)
  set_fact:
    keycloak_realm_manager_fact: "{{ krm_s_result.resources[0].data.username|b64decode }}"
    keycloak_realm_manager_password_fact: "{{ krm_s_result.resources[0].data.password|b64decode }}"
