---

# Expose ansible version
- debug:
    var: ansible_version.full

# Basic pre-playbook prerequisites.
# We need the openshift/kubernetes module amongst other things...

- name: Install prerequisite Python modules
  pip:
    name:
    - openshift==0.10.0
    - jmespath==0.9.4
    extra_args: --user

# If it looks like we're deploying to OpenShift
# we need to use the k8s authentication module to login
# and obtain an API key.
- include_tasks: login.yaml
  when: okd_master_hostname is defined

# A kubernetes (or OpenShift) host and an API key must be set.
# We will either have authenticated against an OpenShift server
# or the AWX kubernetes credentials will have injected suitable
# values for the K8S_AUTH_HOST and K8S_AUTH_API_KEY environment variables.
# Either way the ansible variables 'k8s_auth_host' and
# 'k8s_auth_api_key' will have been set.
- name: Assert authentication
  assert:
    that:
    - k8s_auth_host|length > 0
    - k8s_auth_api_key|length > 0

# Go...

- include_tasks: deploy.yaml
  when: fs_state|string == 'present'
- include_tasks: undeploy.yaml
  when: fs_state|string == 'absent'

# If it looks like we're deploying to OpenShift
# we now need to logout...
- include_tasks: logout.yaml
  when: okd_master_hostname is defined
