---

# Un-deploy (uninstall) Fragnet Search.
#
# To un-deploy Fragnet Search, the fastest way is to
# simply delete the namespace.

- block:

  - name: Delete namespace
    k8s:
      state: absent
      definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
      wait: yes

  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"

# Clean-up the infrastructure

- name: Remove Keycloak Fragnet Search Client
  local_action:
    module: keycloak_client
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_server_url }}"
    auth_realm: master
    auth_username: "{{ keycloak_admin }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ keycloak_realm }}"
    client_id: "{{ fs_keycloak_client_id }}"
    state: absent
