---

# Details of the Services image
fs_flour_services_image: squonk/fragnet-services
# Details of the UI image (which needs an image pull-secret)
fs_flavour_ui_image: registry.gitlab.com/informaticsmatters/fragnet-ui

fs_sa: fragnet-search
fs_sa_psp: im-core-unrestricted

fs_node_purpose: application
fs_pod_ready_timeout: 600
