---

# Details of the Services image
fs_flavour_services_image: squonk/fragnet-services
# Details of the UI image (which needs an image pull-secret)
fs_flavour_ui_image: registry.gitlab.com/informaticsmatters/fragnet-ui

fs_cert_issuer: production
fs_sa: fragnet-search
fs_sa_psp: im-core-unrestricted

fs_pod_ready_timeout: 600

# Pod requests and limits.
# Requests are required, limits can be set to 0 to avoid a limit.

fs_service_cpu_request: 1000m
fs_service_cpu_limit: 1000m
fs_service_mem_request: 4Gi
fs_service_mem_limit: 8Gi

fs_ui_cpu_request: 100m
fs_ui_cpu_limit: 500m
fs_ui_mem_request: 2Gi
fs_ui_mem_limit: 2Gi
