---

# Gets the public key from a names Keycloak Realm.
#
# Sets the facts: -
#
# - keycloak_realm_public_key_fact
#
# Expects: -
#
# - keycloak_server_url (i.e. 'https://{{ hostname }}/auth')
# - keycloak_realm_name

- name: Assert variables
  assert:
    that:
    - keycloak_server_url is defined
    - keycloak_server_url|length > 0
    - keycloak_realm_name is defined
    - keycloak_realm_name|length > 0

- name: Display Keycloak URL
  debug:
    var: keycloak_server_url

- name: Get Keycloak Realm Public Key ({{ keycloak_realm_name }} realm)
  uri:
    url: "{{ keycloak_server_url }}/auth/realms/{{ keycloak_realm_name }}/"
    method: GET
  register: result
  changed_when: no

- name: Set Public Key fact
  set_fact:
    keycloak_realm_public_key_fact: "{{ result.json.public_key }}"

- name: Display Public Key
  debug:
    var: keycloak_realm_public_key_fact
