---

# Sets a number of facts: -
#
# - keycloak_realm_manager_fact
# - keycloak_realm_manager_password_fact
#
# Expects: -
#
# - realm_namespace
# - realm_name

- name: Assert variables
  assert:
    that:
    - realm_namespace is defined
    - realm_namespace|length > 0
    - realm_name is defined
    - realm_name|length > 0

- name: Get Keycloak Realm manager secrets (from '{{ realm_namespace }}' namespace)
  k8s_info:
    kind: Secret
    name: manager-{{ realm_name }}
    namespace: "{{ realm_namespace }}"
  register: krm_s_result

- name: Assert Keycloak realm manager secrets
  assert:
    that: krm_s_result.resources|length == 1

# Extract Realm manager details from pre-deployed secrets...

- name: Set Keycloak realm manager facts (from secret)
  set_fact:
    keycloak_realm_manager_fact: "{{ krm_s_result.resources[0].data.username|b64decode }}"
    keycloak_realm_manager_password_fact: "{{ krm_s_result.resources[0].data.password|b64decode }}"
