---

# Common playbook preparation.

# Expose ansible version
- debug:
    var: ansible_version.full

# Basic pre-playbook prerequisites.
# We need the openshift/kubernetes module amongst other things...

- name: Get installed Python packages
  command: pip freeze
  register: python_models

- name: Collect installed Python packages
  set_fact:
    installed_python_packages: >-
      {{ installed_python_packages|default([]) + [item.split('==')[0]] }}
  with: python_models.stdout_lines

- name: Display Python packages
  debug:
    var: installed_python_packages
    verbosity: 3

- name: stop
  assert:
    that: 1 == 2

- name: Install prerequisite Python modules
  pip:
    name:
    - jmespath==0.9.4
    extra_args: --user

# Install required Ansible Galaxy modules

- name: Install Ansible Galaxy modules
  command: ansible-galaxy install -r infrastructure-realm-requirements.yaml
  register: ag_result
  changed_when: "'downloading role' in ag_result.stdout"

# Kubernetes credentials ------------------------------------------------------

# We don't use the Kubernetes credentials directly,
# but we load them into variables here from their
# expected environment variables so that we can assert they've been set.
#
# If we're using OpenShift credentials these environment variables
# will not be set and we will therefore rely on them being set
# from the 'login.yaml' play.

- name: Set initial authentication facts
  set_fact:
    k8s_auth_host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
    k8s_auth_api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
