---

- include_tasks: prep.yaml

# Try to remove the route.
# The namespace must exist.

# A kubernetes (or OpenShift) host and an API key must be set.
# We will either have authenticated against an OpenShift server
# or the AWX kubernetes credentials will have injected suitable
# values for the K8S_AUTH_HOST and K8S_AUTH_API_KEY environment variables.
# Either way the ansible variables 'k8s_auth_host' and
# 'k8s_auth_api_key' will have been set.
- name: Assert authentication
  assert:
    that:
    - k8s_auth_host|length > 0
    - k8s_auth_api_key|length > 0

# Try to add the route (if it does not exist).
# The namespace is expected to exist.

- block:

  - name: Get expected namespace
    k8s_info:
      kind: Namespace
      name: "{{ fs_namespace }}"
    register: namespace_info

  - name: Assert namespace exists
    assert:
      that: namespace_info.resources|length > 0
      fail_msg: Namespace '{{ fs_namespace }}' does not exist

  - name: Remove application Ingress
    k8s:
      definition: "{{ lookup('template', 'ingress.yaml.j2') }}"
      state: absent
      wait: yes

  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"
